[package]
name = "bevy_examples"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
readme.workspace = true
publish = false

[dependencies]
bevy_motiongfx = { workspace = true, features = ["remote"] }
bevy = { workspace = true, default-features = true, features = [
    "bevy_remote",
]}

[lints]
workspace = true
