[package]
name = "typst_motiongfx"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
publish = false
description = "Typst math and text supporting kurbo BezPaths for MotionGfx animations"

[dependencies]
typst = "0.14"
typst-as-lib = "0.15"
typst-kit = { version = "0.14", default-features = false, features = ["fonts", "embed-fonts"] }
ttf-parser = "0.25"
peniko = { workspace = true, features = ["std"] }
mitex = "0.2"

[lints]
workspace = true
